### ISSUE TITLE
Easily bypass-able.

### ISSUE THREAD

**Issue by ghost** [Lilmac12312/cNoHacks#3]

**Comment by ghost** [comment]
Kill-Aura has the option to ignore mobs and their is also a minecraft code to see how long the entity has been alive.

Use a NPC lib.

**Comment by Lilmac12312** [comment]
This is a open source for those who wish to contribute and improve it.

**Comment by ghost** [comment]
I'd contribute if the code was a bit nicer and not mcpvp's spam check.

something like this but not fully (current my anti-cheat)
https://www.youtube.com/watch?v=P1lsEQAhgCU

**Comment by Lilmac12312** [comment]
As I said, open code for anyone to add onto or clean up.
